listener 1883
allow_anonymous false
password_file /mosquitto/config/password_file

listener 9001
protocol websockets

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# 연결 제한
max_connections 100
max_inflight_messages 20
